create table if not exists newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  status text not null default 'pending',
  consent_text text not null,
  created_at timestamptz not null default now()
);

create table if not exists news_items (
  id text primary key,
  slug text not null unique,
  category text not null,
  title text not null,
  summary text not null,
  source_name text not null,
  source_url text not null,
  canonical_url text not null unique,
  image_url text,
  image_credit text,
  published_at timestamptz not null,
  fetched_at timestamptz not null default now(),
  status text not null default 'published',
  summary_method text not null default 'feed'
);

create index if not exists idx_news_items_status_published_at
on news_items(status, published_at desc);

create table if not exists source_runs (
  source_name text primary key,
  feed_url text not null,
  status text not null,
  item_count integer not null default 0,
  message text,
  checked_at timestamptz not null default now()
);

create table if not exists newsletter_dispatches (
  id bigint generated by default as identity primary key,
  recipient_count integer not null default 0,
  status text not null,
  provider_message text,
  created_at timestamptz not null default now()
);

alter table newsletter_subscribers enable row level security;
alter table news_items enable row level security;
alter table source_runs enable row level security;
alter table newsletter_dispatches enable row level security;
